out_path: ../
content_path: ../_content
template_path: templates
template_static_path: ../assets
default_template: template-doc.html
# default_pdf_template: template-pdf.html


cover_page:
    name: Home
    html: index.html
    template: template-home.html
    sidebar: disabled


targets:
    -   name: en
        display_name: Welcome
        filters:
            - demote_headers
            - link_replacement
        demote_headers_pdf_only: true
        link_re_subs: 
            {"../([0-9]{4}-[a-z0-9-]+)/([0-9]{4}-[a-z0-9-]+).md": "/rfcs/\\1/",
             "..(/asn1/.*?.asn)": "/rfcs\\1.html"}

pages:

# QuickStart ---------------------------------------------------------------------

    -   name: Docs Overview
        funnel: Docs
        doc_type: Overview
        html: overview.html
        md: overview.md
        template: template-doc.html
        blurb: Welcome to the Interledger documentation. Here you can learn how Interledger works and how to start building with it.
        targets:
            - en            

    -   name: Getting Started
        funnel: Docs
        doc_type: Overview
        html: getting-started.html
        md: getting-started.md
        template: template-doc.html
        blurb: This tutorial will help you start an Interledger node locally on your computer and create a local ILP test network.
        targets:
            - en

    -   name: Sending Value Programmatically
        funnel: Docs
        doc_type: Overview
        html: sending-value-programmatically.html
        md: sending-value-programmatically.md
        template: template-doc.html
        blurb: This tutorial shows how to send value over ILP using the SPSP API.
        targets:
            - en

# Community & resources ---------------------------------------------------------------------

    -   name: Get Involved
        funnel: Docs
        doc_type: Community Resources
        html: community.html
        md: community.md
        template: template-doc.html
        targets:
            - en  

    -   name: Libraries &amp; Tools
        funnel: Docs
        doc_type: Community Resources
        html: libraries.html
        md: libraries.md
        template: template-doc.html
        blurb: Build Interledger applications.
        targets:
            - en            

    -   name: ILP Summit 2019 Videos
        funnel: Docs
        doc_type: Community Resources
        html: summit-2019.html
        md: summit-2019.md
        template: template-doc.html
        blurb: The 2019 summit brought together developers, entrepreneurs, and researchers in San Francisco for two days of sharing, building, and learning. Here you can find the recordings of the sessions and talks. Enjoy!
        targets:
            - en  



# Specs ---------------------------------------------------------------------

    -   name: Interledger Protocol V4 (ILPv4)
        funnel: Docs
        doc_type: Specs
        html: rfcs/0027-interledger-protocol-4/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0027-interledger-protocol-4/0027-interledger-protocol-4.md
        template: template-spec.html
        targets:
            - en   

    -   name: ILP Addresses
        funnel: Docs
        doc_type: Specs
        html: rfcs/0015-ilp-addresses/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0015-ilp-addresses/0015-ilp-addresses.md
        template: template-spec.html
        targets:
            - en   

    -   name: STREAM
        funnel: Docs
        doc_type: Specs
        html: rfcs/0029-stream/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0029-stream/0029-stream.md
        template: template-spec.html
        targets:
            - en   

    -   name: Simple Payment Setup Protocol (SPSP)
        funnel: Docs
        doc_type: Specs
        html: rfcs/0009-simple-payment-setup-protocol/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md
        template: template-spec.html
        targets:
            - en 

    -   name: Payment Pointers
        funnel: Docs
        doc_type: Specs
        html: rfcs/0026-payment-pointers/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0026-payment-pointers/0026-payment-pointers.md
        template: template-spec.html
        targets:
            - en 

    # -   name: Web Monetization
    #     funnel: Docs
    #     doc_type: Specs
    #     html: rfcs/0028-web-monetization/index.html
    #     md: https://raw.githubusercontent.com/interledger/rfcs/master/0028-web-monetization/0028-web-monetization.md
    #     template: template-spec.html
    #     targets:
    #         - en 

    -   name: Notes on OER Encoding
        funnel: Docs
        doc_type: Specs
        html: rfcs/0030-notes-on-oer-encoding/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0030-notes-on-oer-encoding/0030-notes-on-oer-encoding.md
        template: template-spec.html
        targets:
            - en 

    -   name: Dynamic Configuration Protocol (ILDCP)
        funnel: Docs
        doc_type: Specs
        html: rfcs/0031-dynamic-configuration-protocol/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0031-dynamic-configuration-protocol/0031-dynamic-configuration-protocol.md
        template: template-spec.html
        targets:
            - en 

    -   name: Peering, Clearing and Settling
        funnel: Docs
        doc_type: Specs
        html: rfcs/0032-peering-clearing-settlement/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0032-peering-clearing-settlement/0032-peering-clearing-settlement.md
        template: template-spec.html
        targets:
            - en 

    -   name: ILP Over HTTP
        funnel: Docs
        doc_type: Specs
        html: rfcs/0035-ilp-over-http/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0035-ilp-over-http/0035-ilp-over-http.md
        template: template-spec.html
        targets:
            - en             

    -   name: SPSP Pull Payments
        funnel: Docs
        doc_type: Specs
        html: rfcs/0036-spsp-pull-payments/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0036-spsp-pull-payments/0036-spsp-pull-payments.md
        template: template-spec.html
        targets:
            - en      



# Specs other ---------------------------------------------------------------------

    -   name: Interledger Architecture
        funnel: Docs
        doc_type: Specs
        html: rfcs/0001-interledger-architecture/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0001-interledger-architecture/0001-interledger-architecture.md
        template: template-spec.html
        targets:
            - en  

    -   name: Paid HTTP APIs
        funnel: Docs
        doc_type: Specs
        html: rfcs/0014-paid-http-apis/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0014-paid-http-apis/0014-paid-http-apis.md
        template: template-spec.html
        targets:
            - en            

    -   name: Connector Risk Mitigations
        funnel: Docs
        doc_type: Specs
        html: rfcs/0018-connector-risk-mitigations/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0018-connector-risk-mitigations/0018-connector-risk-mitigations.md
        template: template-spec.html
        targets:
            - en   

    -   name: Glossary
        funnel: Docs
        doc_type: Specs
        html: rfcs/0019-glossary/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0019-glossary/0019-glossary.md
        template: template-spec.html
        targets:
            - en 

    -   name: Hashed-Timelock Agreements (HTLAs)
        funnel: Docs
        doc_type: Specs
        html: rfcs/0022-hashed-timelock-agreements/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0022-hashed-timelock-agreements/0022-hashed-timelock-agreements.md
        template: template-spec.html
        targets:
            - en 
            
    -   name: avascript Ledger Plugin Interface Version 2
        funnel: Docs
        doc_type: Specs
        html: rfcs/0024-ledger-plugin-interface-2/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0024-ledger-plugin-interface-2/0024-ledger-plugin-interface-2.md
        template: template-spec.html
        targets:
            - en 

    -   name: Relationship between Protocols
        funnel: Docs
        doc_type: Specs
        html: rfcs/0033-relationship-between-protocols/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0033-relationship-between-protocols/0033-relationship-between-protocols.md
        template: template-spec.html
        targets:
            - en             

    -   name: Interledger Node - Requirements Specification
        funnel: Docs
        doc_type: Specs
        html: rfcs/0034-connector-requirements/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0034-connector-requirements/0034-connector-requirements.md
        template: template-spec.html
        targets:
            - en    

    -   name: SPSP Invoices
        funnel: Docs
        doc_type: Specs
        html: rfcs/0037-spsp-invoices/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/0037-spsp-invoices/0037-spsp-invoices.md
        template: template-spec.html
        targets:
            - en  


# ASN ---------------------------------------------------------------------

    -   name: Interledger ASN.1
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/index.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/README.md
        template: template-spec.html
        targets:
            - en  

    -   name: BilateralTransferProtocol.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/BilateralTransferProtocol.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/BilateralTransferProtocol.asn
        template: template-asn.html
        targets:
            - en              

    -   name: DynamicConfigurationProtocol.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/DynamicConfigurationProtocol.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/DynamicConfigurationProtocol.asn
        template: template-asn.html
        targets:
            - en  

    -   name: GenericTypes.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/GenericTypes.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/GenericTypes.asn
        template: template-asn.html
        targets:
            - en 

    -   name: InterledgerErrorData.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/InterledgerErrorData.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/InterledgerErrorData.asn
        template: template-asn.html
        targets:
            - en 

    -   name: InterledgerPacket.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/InterledgerPacket.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/InterledgerPacket.asn
        template: template-asn.html
        targets:
            - en 

    -   name: InterledgerPaymentRequest.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/InterledgerPaymentRequest.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/InterledgerPaymentRequest.asn
        template: template-asn.html
        targets:
            - en 

    -   name: InterledgerProtocol.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/InterledgerProtocol.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/InterledgerProtocol.asn
        template: template-asn.html
        targets:
            - en 

    -   name: InterledgerQuotingProtocol.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/InterledgerQuotingProtocol.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/InterledgerQuotingProtocol.asn
        template: template-asn.html
        targets:
            - en 

    -   name: InterledgerTypes.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/InterledgerTypes.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/InterledgerTypes.asn
        template: template-asn.html
        targets:
            - en 

    -   name: LegacyInterledgerProtocol.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/LegacyInterledgerProtocol.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/LegacyInterledgerProtocol.asn
        template: template-asn.html
        targets:
            - en

    -   name: PreSharedKeyV2.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/PreSharedKeyV2.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/PreSharedKeyV2.asn
        template: template-asn.html
        targets:
            - en            

    -   name: Stream.asn
        funnel: Docs
        doc_type: ASN
        html: rfcs/asn1/Stream.asn.html
        md: https://raw.githubusercontent.com/interledger/rfcs/master/asn1/Stream.asn
        template: template-asn.html
        targets:
            - en



# -------------------- Style Checker Rules ------------------------
word_substitutions_file: plainlanguage_words.yaml
phrase_substitutions_file: plainlanguage_phrases.yaml

